---
version: 1

# The directory path that is created for log files.
# Note! This only define directories to create. Log file paths are set
# on handlers bellow.
log_file_path: 'logs/'
disable_existing_loggers: False
formatters:
    colorlog:
        '()': 'colorlog.ColoredFormatter'
        format: '[%(cyan)s%(asctime)s%(reset)s] [%(log_color)s%(levelname)s]%(reset)s %(name)s:%(message)s'
        datefmt: '%H:%M:%S'
    long:
        format: "%(asctime)s,%(msecs)d %(levelname)-8s [%(name)s.%(funcName)s:%(lineno)d] %(threadName)s:%(message)s"
    default:
        format: "%(asctime)s,%(msecs)d %(levelname)-8s %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
        level: DEBUG

    test_case_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: default
        filename: ./logs/test_case.log
        maxBytes: 1048576 # 1MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default
        filename: ./logs/debug.log
        maxBytes: 1048576 # 1MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: default
        filename: ./logs/info.log
        maxBytes: 1048576 # 1MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: default
        filename: ./logs/errors.log
        maxBytes: 1048576 # 1MB
        backupCount: 20
        encoding: utf8

    websocket:
        class: logging.StreamHandler
        level: INFO
        formatter: default

loggers:
    # Separate logger for test cases. Everything that is logged
    # on tests will go to separate file. Logs will be propagated
    # also on root logger too.
    test_case:
        handlers: [console, test_case_file_handler]

    websocket:
        handlers: [websocket]
root:
    # This sets the max level of logging for all logger and handers.
    # I.e. if you set level WARNING here, all loggers will get only WARNING and
    # above (so error, critical) logs. Set debug here to get debug logs.
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
...
